server:
  port: 8050


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 1
        max-concurrency: 10
    template:
      default-receive-queue: pedido-event